behaviors:
  LevelKoala:
    trainer_type: ppo
    hyperparameters:
      batch_size: 5120
      buffer_size: 409600
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 10
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        encoding_size: 256
        learning_rate: 0.0003
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: true
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 2000
      window: 30
      play_against_latest_model_ratio: 0.15
      initial_elo: 1200.0
